[package]
name = "ygo"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ygo"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2"
cbindgen = "0.20"

[build-dependencies]
cbindgen = "0.20"